# Generated by Django 4.1.13 on 2024-03-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
