# Generated by Django 4.1.13 on 2024-03-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth_dare', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
